[window]
width = 960
height = 600
growth_increment = 80

[generation.large]
fuel_range = [2, 5]
road_chance = 0.8
road_length = 20.0
merge_range = 18.0
organic_angle = 15
child_chance = 0.2

[generation.small]
fuel_range = [1, 2]
road_chance = 0.5
road_length = 8
merge_range = 6
organic_angle = 15
child_chance = 0.3
